In [1]:
# ! pip install numpy

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5])

In [4]:
print(x)

[1 2 3 4 5]


In [21]:
x = np.array([1,2,3,4,5])
print(x.ndim)

x = arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(x.ndim)

1
2


In [6]:
y = np.array([1,2,3,4,5,"sai"])

print(y, type(y))

['1' '2' '3' '4' '5' 'sai'] <class 'numpy.ndarray'>


In [7]:
x = arr = np.array([11, 22, 33])

print(x[0])

11


In [8]:
x = arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(x[0])
print(x[1][2])     # print(x[1,2])

[1 2 3 4 5]
8


In [9]:
arr = np.array(["sai", "preetham", "krishna", "chaitanya", "kishore", "suresh"])

print(arr[1:5])           # index values -> 1, 2, 3, 4

['preetham' 'krishna' 'chaitanya' 'kishore']


In [10]:
arr = np.array(["sai", "preetham", "krishna", "chaitanya", "kishore", "suresh"])

print(arr[1:6:2])        # index values -> 1, 1+2=3, 3+2=5

['preetham' 'chaitanya' 'suresh']


In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [12]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

print(arr[1:])
print()
print(arr[1:, 2])
print()
print(arr[1:, 2:4])

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 8 13 18]

[[ 8  9]
 [13 14]
 [18 19]]


In [13]:
x = 5.2

print(int(x))

5


In [14]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)

[1 2 3]


In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

print(arr.shape)

(4, 5)


In [16]:
print(type(arr.shape))

<class 'tuple'>


In [17]:
print(arr.shape[0])
print(arr.shape[1])

4
5


In [18]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [19]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

for i in arr:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
